Repository FromDoppler/doppler-mercadopago-api, pull requests merged in 2022-05, with the labels that each got.

#3 [DAT-913] - Install MercadoPago SDK and initial configuration
  Doppler.MercadoPagoApi.Test/Doppler.MercadoPagoApi.Test.csproj
  Doppler.MercadoPagoApi/Doppler.MercadoPagoApi.csproj
  Doppler.MercadoPagoApi/Startup.cs
  Doppler.MercadoPagoApi/appsettings.json
Labels: size/XS

#4 [DAT-912] - Create empty Payment controller
  Doppler.MercadoPagoApi/Controllers/PaymentController.cs
Labels: size/S

#5 [DAT-919] remove unnecesary code
  Doppler.MercadoPagoApi.Test/AuthorizationTest.cs
  Doppler.MercadoPagoApi.Test/Doppler.MercadoPagoApi.Test.csproj
  Doppler.MercadoPagoApi.Test/HttpResponseMessageExtensions.cs
  Doppler.MercadoPagoApi.Test/IntegrationTest1.cs
  Doppler.MercadoPagoApi.Test/UnitTest1.cs
  Doppler.MercadoPagoApi/Controllers/HelloController.cs
  Doppler.MercadoPagoApi/Controllers/WeatherForecastController.cs
  Doppler.MercadoPagoApi/Dockerfile
  Doppler.MercadoPagoApi/DopplerSecurity/ConfigureDopplerSecurityOptions.cs
  Doppler.MercadoPagoApi/DopplerSecurity/DopplerAuthorizationRequirement.cs
  Doppler.MercadoPagoApi/DopplerSecurity/DopplerSecurityDefaults.cs
  Doppler.MercadoPagoApi/DopplerSecurity/DopplerSecurityOptions.cs
  Doppler.MercadoPagoApi/DopplerSecurity/DopplerSecurityServiceCollectionExtensions.cs
  Doppler.MercadoPagoApi/DopplerSecurity/IsOwnResourceAuthorizationHandler.cs
  Doppler.MercadoPagoApi/DopplerSecurity/IsSuperUserAuthorizationHandler.cs
  Doppler.MercadoPagoApi/DopplerSecurity/Policies.cs
  Doppler.MercadoPagoApi/Logging/LogglySetup.cs
  Doppler.MercadoPagoApi/Logging/SerilogSetup.cs
  Doppler.MercadoPagoApi/Program.cs
  Doppler.MercadoPagoApi/Properties/launchSettings.json
  Doppler.MercadoPagoApi/Startup.cs
  Doppler.MercadoPagoApi/Weather/DataService.cs
  Doppler.MercadoPagoApi/Weather/IWeatherForecastService.cs
  Doppler.MercadoPagoApi/Weather/WeatherForecast.cs
  Doppler.MercadoPagoApi/Weather/WeatherForecastService.cs
  README.md
  demo.http
Labels: size/XL

#6 [DAT-919] - chore: remove docs folder and other references
  .vscode/launch.json
  .vscode/tasks.json
  README.md
  docs/dockerhub-webhooks.png
  docs/github-main-protection-rules.png
  docs/github-settings-branches.png
Labels: size/S

#12 [DAT-930] - docs: sequence diagram in readme
  README.md
Labels: size/M

#11 [DAT-918] - Create MercadoPago payment endpoint and services
  Doppler.MercadoPagoApi.Test/Services/MercadoPagoTest.cs
  Doppler.MercadoPagoApi/Controllers/PaymentController.cs
  Doppler.MercadoPagoApi/Models/CardDto.cs
  Doppler.MercadoPagoApi/Models/PaymentRequestDto.cs
  Doppler.MercadoPagoApi/Models/PaymentResponseDto.cs
  Doppler.MercadoPagoApi/Services/IMercadoPagoService.cs
  Doppler.MercadoPagoApi/Services/MercadoPagoService.cs
  Doppler.MercadoPagoApi/Startup.cs
  Doppler.MercadoPagoApi/appsettings.json
Labels: size/L

#20 fix: int development
  Jenkinsfile
Labels: size/XS

#22 [DAT-933] - Add property description
  Doppler.MercadoPagoApi/Controllers/PaymentController.cs
  Doppler.MercadoPagoApi/Models/PaymentRequestDto.cs
Labels: size/XS

#21 [DAT-932] - Add notifications endpoint configuration
  Doppler.MercadoPagoApi/Controllers/PaymentController.cs
  Doppler.MercadoPagoApi/appsettings.Development.json
  Doppler.MercadoPagoApi/appsettings.int.json
  Doppler.MercadoPagoApi/appsettings.json
  Doppler.MercadoPagoApi/appsettings.qa.json
Labels: size/S

#23 [DAT-926] - add fluent validators
  Doppler.MercadoPagoApi.Test/Doppler.MercadoPagoApi.Test.csproj
  Doppler.MercadoPagoApi.Test/TestsValidators/CardDtoValidatorTest.cs
  Doppler.MercadoPagoApi.Test/TestsValidators/PaymentRequestDtoValidatorTest.cs
  Doppler.MercadoPagoApi/Doppler.MercadoPagoApi.csproj
  Doppler.MercadoPagoApi/Startup.cs
  Doppler.MercadoPagoApi/Validators/CardDtoValidator.cs
  Doppler.MercadoPagoApi/Validators/PaymentRequestDtoValidator.cs
Labels: size/L

#24 [DAT-935] Create get payment endpoint
  Doppler.MercadoPagoApi.Test/Services/MercadoPagoTest.cs
  Doppler.MercadoPagoApi/Controllers/PaymentController.cs
  Doppler.MercadoPagoApi/Services/IMercadoPagoService.cs
  Doppler.MercadoPagoApi/Services/MercadoPagoService.cs
  Doppler.MercadoPagoApi/Startup.cs
Labels: size/L

#27 [No-Ticket] - Throw an excpetion when the card token can not created
  Doppler.MercadoPagoApi/Services/MercadoPagoService.cs
Labels: size/S

#28 [DAT-944] - Add email security validation
  Doppler.MercadoPagoApi.Test/Services/MercadoPagoTest.cs
  Doppler.MercadoPagoApi/Controllers/PaymentController.cs
Labels: size/M

#29 [DAT-955] - Add authorization test
  Doppler.MercadoPagoApi.Test/AuthorizationTest.cs
Labels: size/L
